# Generated by Django 4.2 on 2023-05-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
