# Generated by Django 4.2 on 2023-04-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_dislike_artist_like_track_dislike_track_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='artistboard',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='track',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='trackboard',
            name='dislike',
        ),
    ]
