# Generated by Django 4.2 on 2023-04-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_artist_dislike_remove_artistboard_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistboard',
            name='username',
        ),
        migrations.RemoveField(
            model_name='trackboard',
            name='username',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
