# Generated by Django 4.2 on 2023-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_user_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_uri',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
